using System.Collections;



	// WCS 1.1.2
	// GetCapabilities Parser
	namespace GetCapabilites
	{
	/************************************************************************************************************************/
	/*GENERATED by Visual Studio 2013. */
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/wcs/1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/wcs/1.1", IsNullable = false)]
	public partial class Capabilities
	{
		
		
		private ServiceIdentification serviceIdentificationField;
		
		private ServiceProvider serviceProviderField;
		
		private OperationsMetadataOperation[] operationsMetadataField;
		
		private CapabilitiesContents contentsField;
		
		private string versionField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
		public ServiceIdentification ServiceIdentification
		{
			get
			{
				return this.serviceIdentificationField;
			}
			set
			{
				this.serviceIdentificationField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
		public ServiceProvider ServiceProvider
		{
			get
			{
				return this.serviceProviderField;
			}
			set
			{
				this.serviceProviderField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
		[System.Xml.Serialization.XmlArrayItemAttribute("Operation", IsNullable = false)]
		public OperationsMetadataOperation[] OperationsMetadata
		{
			get
			{
				return this.operationsMetadataField;
			}
			set
			{
				this.operationsMetadataField = value;
			}
		}
		
		/// <remarks/>
		public CapabilitiesContents Contents
		{
			get
			{
				return this.contentsField;
			}
			set
			{
				this.contentsField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string version
		{
			get
			{
				return this.versionField;
			}
			set
			{
				this.versionField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/1.1", IsNullable = false)]
	public partial class ServiceIdentification
	{
		
		private string titleField;
		
		private string abstractField;
		
		private string[] keywordsField;
		
		private ServiceIdentificationServiceType serviceTypeField;
		
		private string serviceTypeVersionField;
		
		private string feesField;
		
		private string accessConstraintsField;
		
		/// <remarks/>
		public string Title
		{
			get
			{
				return this.titleField;
			}
			set
			{
				this.titleField = value;
			}
		}
		
		/// <remarks/>
		public string Abstract
		{
			get
			{
				return this.abstractField;
			}
			set
			{
				this.abstractField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("Keyword", IsNullable = false)]
		public string[] Keywords
		{
			get
			{
				return this.keywordsField;
			}
			set
			{
				this.keywordsField = value;
			}
		}
		
		/// <remarks/>
		public ServiceIdentificationServiceType ServiceType
		{
			get
			{
				return this.serviceTypeField;
			}
			set
			{
				this.serviceTypeField = value;
			}
		}
		
		/// <remarks/>
		public string ServiceTypeVersion
		{
			get
			{
				return this.serviceTypeVersionField;
			}
			set
			{
				this.serviceTypeVersionField = value;
			}
		}
		
		/// <remarks/>
		public string Fees
		{
			get
			{
				return this.feesField;
			}
			set
			{
				this.feesField = value;
			}
		}
		
		/// <remarks/>
		public string AccessConstraints
		{
			get
			{
				return this.accessConstraintsField;
			}
			set
			{
				this.accessConstraintsField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
	public partial class ServiceIdentificationServiceType
	{
		
		private string codeSpaceField;
		
		private string valueField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string codeSpace
		{
			get
			{
				return this.codeSpaceField;
			}
			set
			{
				this.codeSpaceField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/1.1", IsNullable = false)]
	public partial class ServiceProvider
	{
		
		private string providerNameField;
		
		private ServiceProviderProviderSite providerSiteField;
		
		private ServiceProviderServiceContact serviceContactField;
		
		/// <remarks/>
		public string ProviderName
		{
			get
			{
				return this.providerNameField;
			}
			set
			{
				this.providerNameField = value;
			}
		}
		
		/// <remarks/>
		public ServiceProviderProviderSite ProviderSite
		{
			get
			{
				return this.providerSiteField;
			}
			set
			{
				this.providerSiteField = value;
			}
		}
		
		/// <remarks/>
		public ServiceProviderServiceContact ServiceContact
		{
			get
			{
				return this.serviceContactField;
			}
			set
			{
				this.serviceContactField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
	public partial class ServiceProviderProviderSite
	{
		
		private string typeField;
		
		private string hrefField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
		public string type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
		public string href
		{
			get
			{
				return this.hrefField;
			}
			set
			{
				this.hrefField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
	public partial class ServiceProviderServiceContact
	{
		
		private string individualNameField;
		
		private string positionNameField;
		
		private ServiceProviderServiceContactContactInfo contactInfoField;
		
		private string roleField;
		
		/// <remarks/>
		public string IndividualName
		{
			get
			{
				return this.individualNameField;
			}
			set
			{
				this.individualNameField = value;
			}
		}
		
		/// <remarks/>
		public string PositionName
		{
			get
			{
				return this.positionNameField;
			}
			set
			{
				this.positionNameField = value;
			}
		}
		
		/// <remarks/>
		public ServiceProviderServiceContactContactInfo ContactInfo
		{
			get
			{
				return this.contactInfoField;
			}
			set
			{
				this.contactInfoField = value;
			}
		}
		
		/// <remarks/>
		public string Role
		{
			get
			{
				return this.roleField;
			}
			set
			{
				this.roleField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
	public partial class ServiceProviderServiceContactContactInfo
	{
		
		private ServiceProviderServiceContactContactInfoPhone phoneField;
		
		private ServiceProviderServiceContactContactInfoAddress addressField;
		
		private ServiceProviderServiceContactContactInfoOnlineResource onlineResourceField;
		
		private string hoursOfServiceField;
		
		private string contactInstructionsField;
		
		/// <remarks/>
		public ServiceProviderServiceContactContactInfoPhone Phone
		{
			get
			{
				return this.phoneField;
			}
			set
			{
				this.phoneField = value;
			}
		}
		
		/// <remarks/>
		public ServiceProviderServiceContactContactInfoAddress Address
		{
			get
			{
				return this.addressField;
			}
			set
			{
				this.addressField = value;
			}
		}
		
		/// <remarks/>
		public ServiceProviderServiceContactContactInfoOnlineResource OnlineResource
		{
			get
			{
				return this.onlineResourceField;
			}
			set
			{
				this.onlineResourceField = value;
			}
		}
		
		/// <remarks/>
		public string HoursOfService
		{
			get
			{
				return this.hoursOfServiceField;
			}
			set
			{
				this.hoursOfServiceField = value;
			}
		}
		
		/// <remarks/>
		public string ContactInstructions
		{
			get
			{
				return this.contactInstructionsField;
			}
			set
			{
				this.contactInstructionsField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
	public partial class ServiceProviderServiceContactContactInfoPhone
	{
		
		private string voiceField;
		
		private string facsimileField;
		
		/// <remarks/>
		public string Voice
		{
			get
			{
				return this.voiceField;
			}
			set
			{
				this.voiceField = value;
			}
		}
		
		/// <remarks/>
		public string Facsimile
		{
			get
			{
				return this.facsimileField;
			}
			set
			{
				this.facsimileField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
	public partial class ServiceProviderServiceContactContactInfoAddress
	{
		
		private string deliveryPointField;
		
		private string cityField;
		
		private string administrativeAreaField;
		
		private uint postalCodeField;
		
		private string countryField;
		
		private string electronicMailAddressField;
		
		/// <remarks/>
		public string DeliveryPoint
		{
			get
			{
				return this.deliveryPointField;
			}
			set
			{
				this.deliveryPointField = value;
			}
		}
		
		/// <remarks/>
		public string City
		{
			get
			{
				return this.cityField;
			}
			set
			{
				this.cityField = value;
			}
		}
		
		/// <remarks/>
		public string AdministrativeArea
		{
			get
			{
				return this.administrativeAreaField;
			}
			set
			{
				this.administrativeAreaField = value;
			}
		}
		
		/// <remarks/>
		public uint PostalCode
		{
			get
			{
				return this.postalCodeField;
			}
			set
			{
				this.postalCodeField = value;
			}
		}
		
		/// <remarks/>
		public string Country
		{
			get
			{
				return this.countryField;
			}
			set
			{
				this.countryField = value;
			}
		}
		
		/// <remarks/>
		public string ElectronicMailAddress
		{
			get
			{
				return this.electronicMailAddressField;
			}
			set
			{
				this.electronicMailAddressField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
	public partial class ServiceProviderServiceContactContactInfoOnlineResource
	{
		
		private string typeField;
		
		private string hrefField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
		public string type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
		public string href
		{
			get
			{
				return this.hrefField;
			}
			set
			{
				this.hrefField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
	public partial class OperationsMetadataOperation
	{
		
		private OperationsMetadataOperationDCP dCPField;
		
		private OperationsMetadataOperationParameter[] parameterField;
		
		private string nameField;
		
		/// <remarks/>
		public OperationsMetadataOperationDCP DCP
		{
			get
			{
				return this.dCPField;
			}
			set
			{
				this.dCPField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("Parameter")]
		public OperationsMetadataOperationParameter[] Parameter
		{
			get
			{
				return this.parameterField;
			}
			set
			{
				this.parameterField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
	public partial class OperationsMetadataOperationDCP
	{
		
		private OperationsMetadataOperationDCPHTTP hTTPField;
		
		/// <remarks/>
		public OperationsMetadataOperationDCPHTTP HTTP
		{
			get
			{
				return this.hTTPField;
			}
			set
			{
				this.hTTPField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
	public partial class OperationsMetadataOperationDCPHTTP
	{
		
		private OperationsMetadataOperationDCPHTTPGet getField;
		
		private OperationsMetadataOperationDCPHTTPPost postField;
		
		/// <remarks/>
		public OperationsMetadataOperationDCPHTTPGet Get
		{
			get
			{
				return this.getField;
			}
			set
			{
				this.getField = value;
			}
		}
		
		/// <remarks/>
		public OperationsMetadataOperationDCPHTTPPost Post
		{
			get
			{
				return this.postField;
			}
			set
			{
				this.postField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
	public partial class OperationsMetadataOperationDCPHTTPGet
	{
		
		private string typeField;
		
		private string hrefField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
		public string type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
		public string href
		{
			get
			{
				return this.hrefField;
			}
			set
			{
				this.hrefField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
	public partial class OperationsMetadataOperationDCPHTTPPost
	{
		
		private string typeField;
		
		private string hrefField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
		public string type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
		public string href
		{
			get
			{
				return this.hrefField;
			}
			set
			{
				this.hrefField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
	public partial class OperationsMetadataOperationParameter
	{
		
		private string[] allowedValuesField;
		
		private string nameField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("Value", IsNullable = false)]
		public string[] AllowedValues
		{
			get
			{
				return this.allowedValuesField;
			}
			set
			{
				this.allowedValuesField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/wcs/1.1")]
	public partial class CapabilitiesContents
	{
		
		private CapabilitiesContentsCoverageSummary coverageSummaryField;
		
		/// <remarks/>
		public CapabilitiesContentsCoverageSummary CoverageSummary
		{
			get
			{
				return this.coverageSummaryField;
			}
			set
			{
				this.coverageSummaryField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/wcs/1.1")]
	public partial class CapabilitiesContentsCoverageSummary
	{
		
		private string titleField;
		
		private string abstractField;
		
		private Keywords keywordsField;
		
		private Metadata metadataField;
		
		private WGS84BoundingBox wGS84BoundingBoxField;
		
		private string[] supportedCRSField;
		
		private string identifierField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
		public string Title
		{
			get
			{
				return this.titleField;
			}
			set
			{
				this.titleField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
		public string Abstract
		{
			get
			{
				return this.abstractField;
			}
			set
			{
				this.abstractField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
		public Keywords Keywords
		{
			get
			{
				return this.keywordsField;
			}
			set
			{
				this.keywordsField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
		public Metadata Metadata
		{
			get
			{
				return this.metadataField;
			}
			set
			{
				this.metadataField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
		public WGS84BoundingBox WGS84BoundingBox
		{
			get
			{
				return this.wGS84BoundingBoxField;
			}
			set
			{
				this.wGS84BoundingBoxField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("SupportedCRS")]
		public string[] SupportedCRS
		{
			get
			{
				return this.supportedCRSField;
			}
			set
			{
				this.supportedCRSField = value;
			}
		}
		
		/// <remarks/>
		public string Identifier
		{
			get
			{
				return this.identifierField;
			}
			set
			{
				this.identifierField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/1.1", IsNullable = false)]
	public partial class Keywords
	{
		
		private object keywordField;
		
		/// <remarks/>
		public object Keyword
		{
			get
			{
				return this.keywordField;
			}
			set
			{
				this.keywordField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/1.1", IsNullable = false)]
	public partial class Metadata
	{
		
		private string typeField;
		
		private string hrefField;
		
		private string aboutField;
		
		private string roleField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
		public string type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
		public string href
		{
			get
			{
				return this.hrefField;
			}
			set
			{
				this.hrefField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string about
		{
			get
			{
				return this.aboutField;
			}
			set
			{
				this.aboutField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
		public string role
		{
			get
			{
				return this.roleField;
			}
			set
			{
				this.roleField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/1.1", IsNullable = false)]
	public partial class WGS84BoundingBox
	{
		
		private string lowerCornerField;
		
		private string upperCornerField;
		
		private byte dimensionsField;
		
		/// <remarks/>
		public string LowerCorner
		{
			get
			{
				return this.lowerCornerField;
			}
			set
			{
				this.lowerCornerField = value;
			}
		}
		
		/// <remarks/>
		public string UpperCorner
		{
			get
			{
				return this.upperCornerField;
			}
			set
			{
				this.upperCornerField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public byte dimensions
		{
			get
			{
				return this.dimensionsField;
			}
			set
			{
				this.dimensionsField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/1.1", IsNullable = false)]
	public partial class OperationsMetadata
	{
		
		private OperationsMetadataOperation[] operationField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("Operation")]
		public OperationsMetadataOperation[] Operation
		{
			get
			{
				return this.operationField;
			}
			set
			{
				this.operationField = value;
			}
		}
	}
	}
	//***********************************************************************************************************************/
	// WCS 1.1.2
	// DescribeCoverage Parser
	/***********************************************************************************************************************/
	/// <remarks/>
namespace DescribeCoverageWCS
{
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/wcs/1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/wcs/1.1", IsNullable = false)]
	public partial class CoverageDescriptions
	{
		
		private CoverageDescriptionsCoverageDescription coverageDescriptionField;
		
		/// <remarks/>
		public CoverageDescriptionsCoverageDescription CoverageDescription
		{
			get
			{
				return this.coverageDescriptionField;
			}
			set
			{
				this.coverageDescriptionField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/wcs/1.1")]
	public partial class CoverageDescriptionsCoverageDescription
	{
		
		private string titleField;
		
		private string abstractField;
		
		private Keywords keywordsField;
		
		private string identifierField;
		
		private CoverageDescriptionsCoverageDescriptionDomain domainField;
		
		private CoverageDescriptionsCoverageDescriptionRange rangeField;
		
		private string[] supportedCRSField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
		public string Title
		{
			get
			{
				return this.titleField;
			}
			set
			{
				this.titleField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
		public string Abstract
		{
			get
			{
				return this.abstractField;
			}
			set
			{
				this.abstractField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
		public Keywords Keywords
		{
			get
			{
				return this.keywordsField;
			}
			set
			{
				this.keywordsField = value;
			}
		}
		
		/// <remarks/>
		public string Identifier
		{
			get
			{
				return this.identifierField;
			}
			set
			{
				this.identifierField = value;
			}
		}
		
		/// <remarks/>
		public CoverageDescriptionsCoverageDescriptionDomain Domain
		{
			get
			{
				return this.domainField;
			}
			set
			{
				this.domainField = value;
			}
		}
		
		/// <remarks/>
		public CoverageDescriptionsCoverageDescriptionRange Range
		{
			get
			{
				return this.rangeField;
			}
			set
			{
				this.rangeField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("SupportedCRS")]
		public string[] SupportedCRS
		{
			get
			{
				return this.supportedCRSField;
			}
			set
			{
				this.supportedCRSField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/1.1", IsNullable = false)]
	public partial class Keywords
	{
		
		private object keywordField;
		
		/// <remarks/>
		public object Keyword
		{
			get
			{
				return this.keywordField;
			}
			set
			{
				this.keywordField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/wcs/1.1")]
	public partial class CoverageDescriptionsCoverageDescriptionDomain
	{
		
		private CoverageDescriptionsCoverageDescriptionDomainSpatialDomain spatialDomainField;
		
		/// <remarks/>
		public CoverageDescriptionsCoverageDescriptionDomainSpatialDomain SpatialDomain
		{
			get
			{
				return this.spatialDomainField;
			}
			set
			{
				this.spatialDomainField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/wcs/1.1")]
	public partial class CoverageDescriptionsCoverageDescriptionDomainSpatialDomain
	{
		
		private BoundingBox[] boundingBoxField;
		
		private WGS84BoundingBox wGS84BoundingBoxField;
		
		private CoverageDescriptionsCoverageDescriptionDomainSpatialDomainGridCRS gridCRSField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("BoundingBox", Namespace = "http://www.opengis.net/ows/1.1")]
		public BoundingBox[] BoundingBox
		{
			get
			{
				return this.boundingBoxField;
			}
			set
			{
				this.boundingBoxField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
		public WGS84BoundingBox WGS84BoundingBox
		{
			get
			{
				return this.wGS84BoundingBoxField;
			}
			set
			{
				this.wGS84BoundingBoxField = value;
			}
		}
		
		/// <remarks/>
		public CoverageDescriptionsCoverageDescriptionDomainSpatialDomainGridCRS GridCRS
		{
			get
			{
				return this.gridCRSField;
			}
			set
			{
				this.gridCRSField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/1.1", IsNullable = false)]
	public partial class BoundingBox
	{
		
		private string lowerCornerField;
		
		private string upperCornerField;
		
		private string crsField;
		
		private byte dimensionsField;
		
		/// <remarks/>
		public string LowerCorner
		{
			get
			{
				return this.lowerCornerField;
			}
			set
			{
				this.lowerCornerField = value;
			}
		}
		
		/// <remarks/>
		public string UpperCorner
		{
			get
			{
				return this.upperCornerField;
			}
			set
			{
				this.upperCornerField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string crs
		{
			get
			{
				return this.crsField;
			}
			set
			{
				this.crsField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public byte dimensions
		{
			get
			{
				return this.dimensionsField;
			}
			set
			{
				this.dimensionsField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/1.1", IsNullable = false)]
	public partial class WGS84BoundingBox
	{
		
		private string lowerCornerField;
		
		private string upperCornerField;
		
		private byte dimensionsField;
		
		/// <remarks/>
		public string LowerCorner
		{
			get
			{
				return this.lowerCornerField;
			}
			set
			{
				this.lowerCornerField = value;
			}
		}
		
		/// <remarks/>
		public string UpperCorner
		{
			get
			{
				return this.upperCornerField;
			}
			set
			{
				this.upperCornerField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public byte dimensions
		{
			get
			{
				return this.dimensionsField;
			}
			set
			{
				this.dimensionsField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/wcs/1.1")]
	public partial class CoverageDescriptionsCoverageDescriptionDomainSpatialDomainGridCRS
	{
		
		private string gridBaseCRSField;
		
		private string gridTypeField;
		
		private string gridOriginField;
		
		private string gridOffsetsField;
		
		private string gridCSField;
		
		/// <remarks/>
		public string GridBaseCRS
		{
			get
			{
				return this.gridBaseCRSField;
			}
			set
			{
				this.gridBaseCRSField = value;
			}
		}
		
		/// <remarks/>
		public string GridType
		{
			get
			{
				return this.gridTypeField;
			}
			set
			{
				this.gridTypeField = value;
			}
		}
		
		/// <remarks/>
		public string GridOrigin
		{
			get
			{
				return this.gridOriginField;
			}
			set
			{
				this.gridOriginField = value;
			}
		}
		
		/// <remarks/>
		public string GridOffsets
		{
			get
			{
				return this.gridOffsetsField;
			}
			set
			{
				this.gridOffsetsField = value;
			}
		}
		
		/// <remarks/>
		public string GridCS
		{
			get
			{
				return this.gridCSField;
			}
			set
			{
				this.gridCSField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/wcs/1.1")]
	public partial class CoverageDescriptionsCoverageDescriptionRange
	{
		
		private CoverageDescriptionsCoverageDescriptionRangeField fieldField;
		
		/// <remarks/>
		public CoverageDescriptionsCoverageDescriptionRangeField Field
		{
			get
			{
				return this.fieldField;
			}
			set
			{
				this.fieldField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/wcs/1.1")]
	public partial class CoverageDescriptionsCoverageDescriptionRangeField
	{
		
		private string titleField;
		
		private string identifierField;
		
		private CoverageDescriptionsCoverageDescriptionRangeFieldDefinition definitionField;
		
		private CoverageDescriptionsCoverageDescriptionRangeFieldInterpolationMethods interpolationMethodsField;
		
		private CoverageDescriptionsCoverageDescriptionRangeFieldAxis axisField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
		public string Title
		{
			get
			{
				return this.titleField;
			}
			set
			{
				this.titleField = value;
			}
		}
		
		/// <remarks/>
		public string Identifier
		{
			get
			{
				return this.identifierField;
			}
			set
			{
				this.identifierField = value;
			}
		}
		
		/// <remarks/>
		public CoverageDescriptionsCoverageDescriptionRangeFieldDefinition Definition
		{
			get
			{
				return this.definitionField;
			}
			set
			{
				this.definitionField = value;
			}
		}
		
		/// <remarks/>
		public CoverageDescriptionsCoverageDescriptionRangeFieldInterpolationMethods InterpolationMethods
		{
			get
			{
				return this.interpolationMethodsField;
			}
			set
			{
				this.interpolationMethodsField = value;
			}
		}
		
		/// <remarks/>
		public CoverageDescriptionsCoverageDescriptionRangeFieldAxis Axis
		{
			get
			{
				return this.axisField;
			}
			set
			{
				this.axisField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/wcs/1.1")]
	public partial class CoverageDescriptionsCoverageDescriptionRangeFieldDefinition
	{
		
		private object anyValueField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
		public object AnyValue
		{
			get
			{
				return this.anyValueField;
			}
			set
			{
				this.anyValueField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/wcs/1.1")]
	public partial class CoverageDescriptionsCoverageDescriptionRangeFieldInterpolationMethods
	{
		
		private string interpolationMethodField;
		
		private string defaultField;
		
		/// <remarks/>
		public string InterpolationMethod
		{
			get
			{
				return this.interpolationMethodField;
			}
			set
			{
				this.interpolationMethodField = value;
			}
		}
		
		/// <remarks/>
		public string Default
		{
			get
			{
				return this.defaultField;
			}
			set
			{
				this.defaultField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/wcs/1.1")]
	public partial class CoverageDescriptionsCoverageDescriptionRangeFieldAxis
	{
		
		private CoverageDescriptionsCoverageDescriptionRangeFieldAxisAvailableKeys availableKeysField;
		
		private string identifierField;
		
		/// <remarks/>
		public CoverageDescriptionsCoverageDescriptionRangeFieldAxisAvailableKeys AvailableKeys
		{
			get
			{
				return this.availableKeysField;
			}
			set
			{
				this.availableKeysField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string identifier
		{
			get
			{
				return this.identifierField;
			}
			set
			{
				this.identifierField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/wcs/1.1")]
	public partial class CoverageDescriptionsCoverageDescriptionRangeFieldAxisAvailableKeys
	{
		
		private byte keyField;
		
		/// <remarks/>
		public byte Key
		{
			get
			{
				return this.keyField;
			}
			set
			{
				this.keyField = value;
			}
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/wcs/1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/wcs/1.1", IsNullable = false)]
	public partial class Coverages
	{
		
		private CoveragesCoverage coverageField;
		
		/// <remarks/>
		public CoveragesCoverage Coverage
		{
			get
			{
				return this.coverageField;
			}
			set
			{
				this.coverageField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/wcs/1.1")]
	public partial class CoveragesCoverage
	{
		
		private Reference referenceField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
		public Reference Reference
		{
			get
			{
				return this.referenceField;
			}
			set
			{
				this.referenceField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/1.1", IsNullable = false)]
	public partial class Reference
	{
		
		private string hrefField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
		public string href
		{
			get
			{
				return this.hrefField;
			}
			set
			{
				this.hrefField = value;
			}
		}
	}
}	
	/*******/
	


